### ISSUE TITLE
Multiple Licenses In Documentation Overview

### ISSUE THREAD

**Issue by prestonvasquez** [alpstable/gidari#365]
Determine why we are getting the license copyright in the [documentation overview](https://pkg.go.dev/github.com/alpstable/gidari#pkg-overview). Update the "add-license" script to avoid this behavior.

**Comment by fahimbagar** [comment]
Hi @prestonvasquez, I've checked this issue and I found the reason (well, wild stab in the dark :sweat_smile:).

In the root level (same level as `go.mod`), these 2 go files contain the same lines.
https://github.com/alpstable/gidari/blob/a60b3fbfa25683aefb58e040261eca6f8eb87d44/http.go#L1-L2
https://github.com/alpstable/gidari/blob/a60b3fbfa25683aefb58e040261eca6f8eb87d44/service.go#L1-L2

While in `decode.go`, it doesn't have LICENSE inserted yet.
https://github.com/alpstable/gidari/blob/main/decode.go#L1

I found this interesting information on one of [Golang issue about LICENSE](https://github.com/golang/go/issues/39318#issuecomment-638999906) but relatable to this issue.
> The problem here is that pkg.go.dev only sees the tree rooted at the module (location of the go.mod file). What we actually consume is a zip file of that tree, handed to us by https://proxy.golang.org/. We don't have the repo (although, as you can tell from the site, we do display a link to it). So the license file must appear at the repo root.

So I guess `add-license` needs to be adjusted to write it in 1 file only when it's in the root level.

On another thing to consider, I found it's unusual to add copyright as a package overview. Usually, a package overview should give a summary of what the package is rather than the copyright.
- https://pkg.go.dev/os
- https://pkg.go.dev/io/ioutil

I've checked that the LICENSE for this repo is correct, https://pkg.go.dev/github.com/alpstable/gidari?tab=licenses.

**Comment by fahimbagar** [comment]
Let me know if I could help you with this issue.

**Comment by prestonvasquez** [comment]
@fahimbagar I see. After reading through the go docs, I think what we want to do is to add a root file called `doc.go` with the following:

```go
// Copyright 2022 The Gidari Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0

// Package gidari provides a "web-to-storage" API for batch querying web APIs and persisting the resulting data.
package gidari
```

**Comment by fahimbagar** [comment]
Hi @prestonvasquez, I'd be happy if I could help you with this. Please assign it to me.

I have another info. In https://pkg.go.dev/github.com/fahimbagar/just-useless-module@v1.0.0#pkg-overview, I've put 2 comments with a new line and not. And it gets one without a new line in between.
https://github.com/fahimbagar/just-useless-module/blob/f0c134de4e6c8852f27954b0dea509fffd987172/useless.go#L1-L4
```
/*
Useless Module.
*/
package just_useless_module
```

https://github.com/fahimbagar/just-useless-module/blob/f0c134de4e6c8852f27954b0dea509fffd987172/doc.go#L1-L3
```
// This is just another useless module.

package just_useless_module
```

So here is what I'll do:
1. Add `doc.go` as you said without any new line in between.
2. Fix `add-license` script by adding a new line for other files except `doc.go`.
Let me know if this makes sense to you.
